/// Flutter icons FbClone
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  FbClone
///      fonts:
///       - asset: fonts/FbClone.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class FbClone {
  FbClone._();

  static const _kFontFam = 'FbClone';
  static const String? _kFontPkg = null;

  static const IconData like = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData images = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mss = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData campana = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData videocamera = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData people = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
