name: tv
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.0-155.0.dev <4.0.0"
  flutter: ">=2.0.0 <=3.0.0"

dependencies:
  cached_network_image: ^3.2.3
  connectivity_plus: ^4.0.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^8.0.0
  flutter_svg: ^2.0.7
  fluttertoast: ^8.2.2
  freezed_annotation: ^2.4.1
  go_router: ^10.0.0
  google_fonts: ^5.1.0
  http: ^1.1.0
  intl: ^0.18.1
  json_annotation: ^4.8.1
  provider: ^6.0.5
  shared_preferences: ^2.2.0
  slang: ^3.22.0
  slang_flutter: ^3.22.0
  url_strategy: ^0.2.0

dev_dependencies:
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.3.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.1
  json_serializable: ^6.7.1
  slang_build_runner: ^3.22.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svgs/

flutter_gen:
  output: lib/app/generated/
  integrations:
    flutter_svg: true
